id: P00601791
initial_creation_type: input
source_metadata:
  title: Siṃhamukhā Series
  language: en
  description: 'Texts related to Siṃhamukhā/Siṃhamukhī or Siṃhavaktrā (seng ge gdong
    ma), the Lion-Faced Ḍākinī:'
  volume:
    e0bac0d51c49480cb2c46ad8b35a680c:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Averting Obstacles
    0b0de034b9314e9692d1cba7f1b0ec66:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: History
    67a9bb86ae004932ac4f834254b480e0:
      title: Siṃhamukhā Lineage Prayer
      parent: Lineage Prayers
created_at: '2022-03-01T05:49:02.015312'
last_modified_at: '2022-03-01T05:49:02.015319'
